"""
Shared utilities and constants package for the Merma Optimization application.


This package provides shared utilities and constants used across
the backend and frontend applications.
"""

from shared.constants import (
    API_DESCRIPTION,
    API_VERSION,
    API_TITLE,
    APP_NAME,
    AlertSeverity,
    DATE_FORMAT,
    DATETIME_FORMAT,
    DEFAULT_PAGE_SIZE,
    ISO8601_FORMAT,
    MAX_PAGE_SIZE,
    MIN_PAGE_SIZE,
)

from shared.utils import (
    add_days,
    add_hours,
    calculate_growth_rate,
    calculate_moving_average,
    calculate_percentage,
    camel_to_snake,
    chunk_list,
    convert_to_bool,
    convert_to_float,
    convert_to_int,
    date_range,
    deduplicate_list,
    filter_dict,
    format_date,
    format_datetime,
    generate_api_key,
    generate_hash,
    generate_uuid,
    get_current_date,
    get_current_datetime,
    get_nested_value,
    is_valid_uuid,
    mask_sensitive_data,
    merge_dicts,
    paginate_list,
    parse_date,
    parse_json,
    round_decimal,
    safe_divide,
    sanitize_string,
    set_nested_value,
    snake_to_camel,
    to_iso8601,
    to_json,
    truncate_string,
    validate_email,
    validate_password,
    validate_username,
    verify_hash,
)

__all__ = [
    # Constants
    "API_VERSION",
    "API_TITLE",
    "API_DESCRIPTION",
    "APP_NAME",
    "DATE_FORMAT",
    "DATETIME_FORMAT",
    "ISO8601_FORMAT",
    "DEFAULT_PAGE_SIZE",
    "MAX_PAGE_SIZE",
    "MIN_PAGE_SIZE",
    "AlertSeverity",
    # Utils
    "generate_uuid",
    "generate_api_key",
    "generate_hash",
    "verify_hash",
    "parse_date",
    "format_datetime",
    "format_date",
    "to_iso8601",
    "get_current_datetime",
    "get_current_date",
    "add_days",
    "add_hours",
    "date_range",
    "validate_email",
    "validate_username",
    "validate_password",
    "sanitize_string",
    "truncate_string",
    "round_decimal",
    "calculate_percentage",
    "safe_divide",
    "convert_to_float",
    "convert_to_int",
    "convert_to_bool",
    "parse_json",
    "to_json",
    "paginate_list",
    "filter_dict",
    "merge_dicts",
    "get_nested_value",
    "set_nested_value",
    "camel_to_snake",
    "snake_to_camel",
    "chunk_list",
    "deduplicate_list",
    "calculate_moving_average",
    "calculate_growth_rate",
    "is_valid_uuid",
    "mask_sensitive_data",
]
